version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
