version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install python-dev
      - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - run: sudo python get-pip.py
      - run: pip install --upgrade --user awscli
      - run: pip install --upgrade --user awsebcli
      - run: export PATH=~/.local/bin:$PATH
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: ~/.local/bin/eb deploy
